using Plots; using LinearAlgebra
## Generate data
xv=0.1:0.3:3     # grid of regressors 
y = xv.^3        # response generated by any function you may like...
yn= y + randn(size(xv)) # add noise

p=plot(xv,y,linestyle=:dash)
plot!(xv,yn,seriestype=:scatter)
gui() # maybe needed

# TODO
# 1. choose polynomial basis functions up to order "n"
# 2. estimate parameters of the polynomial using least squares.
# 3. show sensitivity of the result to order "n"
# 4. Interpret the result as Bayesian estimates 
# and plot 2std uncertainty bounds on prediction of "y"
# 5. Choose prior N(0,αI) and discuss sensitivity to α
n = 9
W = [(xv).^i for i = 0:n]
X = hcat(W...)
Theta = inv(X'*X)*X'*yn
Y = X*Theta
plot!(xv,Y)
alpha = 10
beta = 1
S = alpha*I + beta*X'*X
inv(S)
m = beta*inv(S)*X'*yn
Y2=X*m
plot!(xv,Y2)
#8. generovat vzorky z N(m,S) a pro kazdy vzorek udelat y,

C = cholesky(S)
Theta2 = m .+ C.L
C.L
Y3 = X*Theta2
plot!(xv,Y3)